### ISSUE TITLE
Not updating systemd service file

### ISSUE THREAD

**Issue by maxenced** [BashtonLtd/puppet-varnish#19]
In case systemd is used (debian 8 for ex), the /etc/default/varnish is not used anymore, and the start line is hardcoded in systemd : 

```
grep Start= /etc/systemd/system/multi-user.target.wants/varnish.service
ExecStart=/usr/sbin/varnishd -a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m
```

So this need to be updated in place of /etc/default/varnish

**Comment by craigwatson** [comment]
Thanks for reporting this, we'll be addressing systemd compatibility in a future module release - apologies for taking over a year to respond!
