### ISSUE TITLE
Add install_options to package spec(?)

### ISSUE THREAD

**Issue by alfaguru** [BashtonLtd/puppet-varnish#23]
Hi, have been having major headaches with installing on a CentOS server where an older version of varnish is in one of the repositories. Finally got round it by patching your module to add install options on the varnish package spec, and then passing a parameter to disable the repo in question.

I don't know if that's the best approach: any other ideas would be welcome. I'm fairly new to Puppet. Puppet version is 3.8.

**Comment by craigwatson** [comment]
Hi,

Apologies for taking over a year to get to this issue - hope you managed to get things sorted!

Admittedly dealing with pre-existing Varnish installations would be out-of-scope for the module, my advice would be to manually uninstall any old version of Varnish before running Puppet.

That said, if there are modifications you'd like to make to the module, please do raise a Pull Request and we'll review them :)

Thanks,
Craig
